services:
  postget-api:
    build: .
    container_name: postget-api
    ports:
      - "8050:8000"
    volumes:
      - ./app:/app        # live code reload (optional)
      - ./latest_post.json:/app/latest_post.json
    restart: unless-stopped

